#ifndef COMMON_H
#define COMMON_H

#include <stdio.h>
#include <stdlib.h>
#include "parser.h"                 /* for token name generated by parser.y */

#define YY_SKIP_YYWRAP

/***************************************************
 * structure definition
 ***************************************************/
#define ATOM_INTEGER 1
struct atom{        
  int type; 
  union{
    int _int;
  }u;
};

struct pair{
  struct s_exp *car;
  struct s_exp *cdr;
};

#define S_EXP_ATOM 1             
#define S_EXP_PAIR 2
struct s_exp{                   
  int type;
  union{
    struct atom *atom;
    struct pair *pair;
  }u;
};

/***************************************************
 * function prototype definition
 ***************************************************/
int yylex(void);
void yyerror(char* s);
void prompt();
int yywrap();

/***************************************************
 * external variable definition
 ***************************************************/
extern char *yytext;               /* lexer input */
extern FILE *yyin;                 /* input file */
extern int interactive;            /* true if interactive mode, false otherwise */

#endif COMMON_H
