#ifndef COMMON_H
#define COMMON_H

#include <stdio.h>
#include <stdlib.h>
#include "parser.h"                 /* for token name generated by parser.y */

#define YY_SKIP_YYWRAP

/***************************************************
 * structure definition
 ***************************************************/
struct pair{
  struct s_exp *car;
  struct s_exp *cdr;
};

#define S_EXP_PAIR 	1
#define S_EXP_INTEGER	2
#define S_EXP_CHARACTER	3
struct s_exp{                   
  int type;
  union{
    struct pair *pair;
    int integer;
    char character;
  }u;
};

/***************************************************
 * function prototype definition
 ***************************************************/
int yylex(void);
void yyerror(char* s);
void prompt();
int yywrap();
struct s_exp *integer2sexp(int i);
struct s_exp *character2sexp(char c);

/***************************************************
 * external variable definition
 ***************************************************/
extern char *yytext;               /* lexer input */
extern FILE *yyin;                 /* input file */
extern int interactive;            /* true if interactive mode, false otherwise */

#endif COMMON_H
