name: action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt install gcc bison flex
      - name: run test
        run: |
          make test
